/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#050816",
        secondary: "#bed0ff",
        tertiary: "#151030",
        "black-100": "#262a33",
        "black-200": "#090325",
        "white-100": "#f3f3f3",
      },

      screens: {
        xs: "450px",
      },
      backgroundImage: {
        "hero-pattern": "url('/polygon-scatter-haikei.svg')",
      },
    },
  },
  safelist: [
    "bg-red-500",
    "text-3xl",
    "lg:text-4xl",
    "blue-text-gradient",
    "green-text-gradient",
    "pink-text-gradient",
    "text-red-800",
    "text-cyan-400",
    "text-green-600",
    "text-pink-200",
    "text-violet-200",
    "text-red-600",
    "green-pink-gradient",
    "active:scale-95",
    "transition-all",
    "shadow-card",
    "p-[2px]",
    "rounded-3xl",
    "animate-pulse",
    "text-4xl",
    "text-gray",
    "h-[60px]",
    "w-[60px]",
    "bg-cover",
    "rounded-full",
    "black-gradient",
    "animate-spin",
    "duration-1000",
    "h-10",
    "w-10",
    "h-12",
    "px-6",
    "bg-slate-700",
    "focus:ring-2",
    "focus:ring-slate-400",
    "text-base",
    "text-white",
    "font-semibold",
    "pointer-events-auto",
    "from-[#070637]",
    "inset-x-0",
    "max-lg:w-[100dvw]",
    "top-0",
    "-translate-y-2/3",
    "bg-gradient-to-t",
    "to-[#0303037a]",
    "pointer-events-none",
    "absolute",
    "bg-[url(/blob1.svg)]",
    "bg-[url(/blob2.svg)]",
    "bg-[url(/blob3.svg)]",
    "bg-[url(/blob4.svg)]",
    "bg-[url(/blob5.svg)]",
    "bg-[url(/blob6.svg)]",
  ],

  plugins: [],
};
